name: RSP-CG specification build

on:
  pull_request:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        include:
          # Add more specifications here as needed
          - source: index.bs
            destination: index.html
          - source: spec/messages.bs
            destination: spec/messages.html

    steps:
      - uses: actions/checkout@v3
      - name: Publish Bikeshed document
        uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          GH_PAGES_BRANCH: gh-pages
          SOURCE: ${{ matrix.source }}
          DESTINATION: ${{ matrix.destination }}
